import os

file_path = "vmalloc_debug.hpp"



def generate_prolog(file, settings):
    file.write("// This file is automatically generated.\n"
               "// Only edit the ENABLE_*-flags flags to turn on/off debug messages from specific modules.\n"
               "// To add a new modules define a new ENABLE_DEBUG_<MODULE> flag here and regenerate the file.\n\n");

    for module, setting in sorted(settings.items()):
        file.write(f"#define ENABLE_DEBUG_{module.upper()} {setting}\n");
    file.write("\n");
    for module, setting in sorted(settings.items()):
        file.write(f"#define DEBUG_{module.upper()}(msg)\n");
    file.write("\n");


def generate_epilog(file, settings):
    file.write("// Changes beyond this point will not affect the generated code.");

    file.write("\n#ifndef NDEBUG\n");
    for module, setting in sorted(settings.items()):
        file.write(f"\t#if ENABLE_DEBUG_{module.upper()} == 1\n");
        file.write(f"\t\t#undef DEBUG_{module.upper()}\n");
        file.write(f"\t\t#define DEBUG_{module.upper()}(msg) std::cout << \"[DEBUG {module.upper()}] \" << msg << std::endl;\n");
        file.write(f"\t#endif\n");
    file.write("#endif\n");

def parse_debug_settings(path):
    settings = dict()
    with open(path, "r") as setting_file:
        for line in setting_file:
            line = line.strip()
            if line.startswith("#define ENABLE_DEBUG_"):
                parts = line.split()
                flag_split = parts[1].split("_")
                if len(flag_split) >= 2:
                    module_name = "_".join(flag_split[2:]).lower()
                    setting = 0
                    if(len(parts) == 3 and parts[2].isdigit()):
                        setting = int(parts[2])

                    if(module_name in settings):
                        print(f"WARING: Removed duplicate debug setting for module '{module_name}'.")
                    settings[module_name] = setting
    return settings

settings = parse_debug_settings(file_path)

file = open(f"{file_path}.progress", "w");

file.write("#pragma once\n\n");
file.write("// clang-format off\n\n");

generate_prolog(file, settings);
generate_epilog(file, settings);

file.write("// clang-format on\n");

file.close();

os.replace(f"{file_path}.progress", file_path);

# Ensure the generated file has the requested permissions (rwx for everyone)
try:
    os.chmod(file_path, 0o777)
except Exception as e:
    print(f"Warning: could not set permissions on {file_path}: {e}")
