#pragma once

// clang-format off

// This file is automatically generated.
// Only edit the ENABLE_*-flags flags to turn on/off debug messages from specific modules.
// To add a new modules define a new ENABLE_DEBUG_<MODULE> flag here and regenerate the file.

#define ENABLE_DEBUG_VAMPPH 0
#define ENABLE_DEBUG_VAMPTR 0
#define ENABLE_DEBUG_VAMSPLT 0

#define DEBUG_VAMPPH(msg)
#define DEBUG_VAMPTR(msg)
#define DEBUG_VAMSPLT(msg)

// Changes beyond this point will not affect the generated code.
#ifndef NDEBUG
	#if ENABLE_DEBUG_VAMPPH == 1
		#undef DEBUG_VAMPPH
		#define DEBUG_VAMPPH(msg) std::cout << "[DEBUG VAMPPH] " << msg << std::endl;
	#endif
	#if ENABLE_DEBUG_VAMPTR == 1
		#undef DEBUG_VAMPTR
		#define DEBUG_VAMPTR(msg) std::cout << "[DEBUG VAMPTR] " << msg << std::endl;
	#endif
	#if ENABLE_DEBUG_VAMSPLT == 1
		#undef DEBUG_VAMSPLT
		#define DEBUG_VAMSPLT(msg) std::cout << "[DEBUG VAMSPLT] " << msg << std::endl;
	#endif
#endif
// clang-format on
